---

- hosts: all
  name: install python and create user
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install python on remote host
      raw: sudo apt-get -y install python
  roles:
    - user
